/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack_queue;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @DisplayName("Test1")
    void pushStack()
    {
        Stack stackTest = new Stack();

    }

    @Test
    @DisplayName("Test2")
    void pushMulValStack()
    {
        stack stackTest = new stack();
        stackTest.push(new stackNode("Audi"));
        stackTest.push(new stackNode("Mercedes"));
        stackTest.push(new stackNode("RangeRover"));
        String result = String.valueOf(stackTest);
        String expected = "{RangeRover}{Mercedes}{Audi}";
        assertEquals(expected , result);
    }


}
