/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sort;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class InsertionSortTest {

    @Test
    public void testInsertionSort() {
        int[] arr1 = {};
        int[] arr2 = {8,4,23,42,16,15};
        int[] arr3 = {10,16,21,5,1};

        int[] testArr1 = {};
        int[] testArr2 = {4,8,15,16,23,42};
        int[] testArr3 = {1,5,10,16,21};

        assertArrayEquals(testArr1, InsertionSort.insertionSort(arr1));
        assertArrayEquals(testArr2, InsertionSort.insertionSort(arr2));
        assertArrayEquals(testArr3, InsertionSort.insertionSort(arr3));
    }

}
