/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import hashtable.structure.HashMap;
import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.*;

public class AppTest {
    HashMap<String , Integer> emptyHashtable;
    HashMap<String , Integer> ages;
    HashMap<String , Integer> groceries;

    @Before
    public void init() {

        emptyHashtable = new HashMap<>();

        ages = new HashMap<>();
        ages.add("Rawzi", 29);
        ages.add("Ali", 29);
        ages.add("Sabreen", 27);
        ages.add("Duaa", 28);

        groceries = new HashMap<>();
        groceries.add("Coffee", 35);
        groceries.add("Tea", 28);
        groceries.add("Bread", 10);
        groceries.add("Yogurt", 17);

    }

    @Test
    public void testEmptyHashMapSize() {
        assertEquals(0, emptyHashtable.getSize());
    }

    @Test
    public void TestHashMapIntegerSize() {
        assertEquals(4, ages.getSize());
    }

    @Test
    public void TestHashMapStringSize() {
        assertEquals(4, groceries.getSize());
    }

    @Test
    public void testEmptyHashMapIsEmpty() {
        assertTrue(emptyHashtable.isEmpty());
    }

    @Test
    public void TestHashMapIntegerIsEmpty() {
        assertFalse(ages.isEmpty());
    }

    @Test
    public void TestHashMapStringIsEmpty() {
        assertFalse(groceries.isEmpty());
    }

    @Test
    public void testEmptyHashMapGet() {
        assertNull(emptyHashtable.get("key"));
    }

    @Test
    public void TestHashMapIntegerGet() {
        assertEquals(Integer.valueOf(29), ages.get("Ali"));
        assertEquals(Integer.valueOf(29), ages.get("Rawzi"));
        assertEquals(Integer.valueOf(28), ages.get("Duaa"));
        assertEquals(Integer.valueOf(27), ages.get("Sabreen"));
    }

    @Test
    public void TestHashTableIntegerContains() {
        assertTrue(ages.contains("Ali"));
        assertFalse(ages.contains("Hasan"));
    }

    @Test
    public void TestHashTableStringContains() {
        assertTrue(groceries.contains("Coffee"));
        assertFalse(groceries.contains("Cheese"));
    }
}
