/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TreeIntersection;

public class App {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {

    }
}
